/* Copyright (c) 2020 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_TRANSACTIONS_TEST_TRANSACTION_TEST_CONSTANTS_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_TRANSACTIONS_TEST_TRANSACTION_TEST_CONSTANTS_H_

namespace catsxp_ads::test {

inline constexpr char kTransactionId[] = "8b742869-6e4a-490c-ac31-31b49130098a";

}  // namespace catsxp_ads::test

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_TRANSACTIONS_TEST_TRANSACTION_TEST_CONSTANTS_H_
