/* Copyright (c) 2020 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_COMMAND_LINE_SWITCHES_ENVIRONMENT_ENVIRONMENT_FLAG_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_COMMAND_LINE_SWITCHES_ENVIRONMENT_ENVIRONMENT_FLAG_UTIL_H_

namespace catsxp_ads {

bool IsProductionEnvironment();

}  // namespace catsxp_ads

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_COMMAND_LINE_SWITCHES_ENVIRONMENT_ENVIRONMENT_FLAG_UTIL_H_
