/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_SHIELDS_CORE_COMMON_CATSXP_SHIELD_LOCALIZED_STRINGS_H_
#define CATSXP_COMPONENTS_CATSXP_SHIELDS_CORE_COMMON_CATSXP_SHIELD_LOCALIZED_STRINGS_H_

#include "components/grit/catsxp_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace catsxp_shields {

inline constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"catsxpShields", IDS_CATSXP_SHIELDS},
    {"catsxpShieldsStandalone", IDS_CATSXP_SHIELDS_STANDALONE},
    {"catsxpShieldsEnable", IDS_CATSXP_SHIELDS_ENABLE},
    {"catsxpShieldsUp", IDS_CATSXP_SHIELDS_UP},
    {"catsxpShieldsDown", IDS_CATSXP_SHIELDS_DOWN},
    {"catsxpShieldsBroken", IDS_CATSXP_SHIELDS_BROKEN},
    {"catsxpShieldsBrokenNote", IDS_CATSXP_SHIELDS_BROKEN_NOTE},
    {"catsxpShieldsAreYouExperiencingIssuesWithThisSiteTitle",
     IDS_CATSXP_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_TITLE},
    {"catsxpShieldsAreYouExperiencingIssuesWithThisSiteDesc1",
     IDS_CATSXP_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_DESC1},
    {"catsxpShieldsAreYouExperiencingIssuesWithThisSiteDesc2",
     IDS_CATSXP_SHIELDS_ARE_YOU_EXPERIENCING_ISSUES_WITH_THIS_SITE_DESC2},
    {"catsxpShieldsEnableAdBlockOnlyMode",
     IDS_CATSXP_SHIELDS_ENABLE_AD_BLOCK_ONLY_MODE},
    {"catsxpShieldsDismissAlert", IDS_CATSXP_SHIELDS_DISMISS_ALERT},
    {"catsxpShieldsIsThisSiteWorkingCorrectlyNowTitle",
     IDS_CATSXP_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_TITLE},
    {"catsxpShieldsIsThisSiteWorkingCorrectlyNowDesc",
     IDS_CATSXP_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_DESC},
    {"catsxpShieldsIsThisSiteWorkingCorrectlyNowLooksGood",
     IDS_CATSXP_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_LOOKS_GOOD},
    {"catsxpShieldsIsThisSiteWorkingCorrectlyNowReportSite",
     IDS_CATSXP_SHIELDS_IS_THIS_SITE_WORKING_CORRECTLY_NOW_REPORT_SITE},
    {"catsxpShieldsAdBlockOnlyModeEnabledTitle",
     IDS_CATSXP_SHIELDS_AD_BLOCK_ONLY_MODE_ENABLE_TITLE},
    {"catsxpShieldsAdBlockOnlyModeEnabledDesc",
     IDS_CATSXP_SHIELDS_AD_BLOCK_ONLY_MODE_ENABLE_DESC},
    {"catsxpShieldsAdsBlockedNote", IDS_CATSXP_SHIELDS_ADS_BLOCKED_NOTE},
    {"catsxpShieldsBlockedNote", IDS_CATSXP_SHIELDS_BLOCKED_NOTE},
    {"catsxpShieldsNOTBlockedNote", IDS_CATSXP_SHIELDS_NOT_BLOCKED_NOTE},
    {"catsxpShieldsAdvancedCtrls", IDS_CATSXP_SHIELDS_ADVANCED_CTRLS},
    {"catsxpShieldSettingsDescription", IDS_CATSXP_SHIELD_SETTINGS_DESCRIPTION},
    {"catsxpShieldsGlobalSettingsTitle",
     IDS_CATSXP_SHIELDS_GLOBAL_SETTINGS_TITLE},
    {"catsxpShieldsChangeDefaults", IDS_CATSXP_SHIELDS_CHANGE_DEFAULTS},
    {"catsxpShieldsShowAllBlockedElems",
     IDS_CATSXP_SHIELDS_SHOW_ALL_BLOCKED_ELEMENTS},
    {"catsxpShieldsCustomizeAdblockLists",
     IDS_CATSXP_SHIELDS_CUSTOMIZE_ADBLOCK_LISTS},
    {"catsxpShieldsConnectionsUpgraded", IDS_CATSXP_SHIELDS_CONNECTIONS_UPGRADED},
    {"catsxpShieldsHTTPSEnable", IDS_CATSXP_SHIELDS_HTTPS_ENABLE},
    {"catsxpShieldsScriptsBlocked", IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED},
    {"catsxpShieldsScriptsBlockedOverridden",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN},
    {"catsxpShieldsScriptsBlockedOverriddenByExt",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_EXTENSION},
    {"catsxpShieldsScriptsBlockedOverriddenByPolicy",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_POLICY},
    {"catsxpShieldsScriptsBlockedOverriddenByAllowlist",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_ALLOWLIST},
    {"catsxpShieldsScriptsBlockedOverriddenBySupervisor",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_SUPERVISOR},
    {"catsxpShieldsScriptsBlockedOverriddenByPWA",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_OVERRIDDEN_BY_PWA},
    {"catsxpShieldsScriptsBlockedEnable",
     IDS_CATSXP_SHIELDS_SCRIPTS_BLOCKED_ENABLE},
    {"catsxpShieldsTrackersAndAds", IDS_CATSXP_SHIELDS_TRACKERS_AND_ADS},
    {"catsxpShieldsTrackersAndAdsBlockedStd",
     IDS_CATSXP_SHIELDS_TRACKERS_AND_ADS_BLOCKED_STD},
    {"catsxpShieldsTrackersAndAdsBlockedAgg",
     IDS_CATSXP_SHIELDS_TRACKERS_AND_ADS_BLOCKED_AGG},
    {"catsxpShieldsTrackersAndAdsAllowAll",
     IDS_CATSXP_SHIELDS_TRACKERS_AND_ADS_ALLOW_ALL},
    {"catsxpShieldsThirdPartyCookiesBlocked",
     IDS_CATSXP_SHIELDS_THIRD_PARTY_COOKIES_BLOCKED},
    {"catsxpShieldsForgetFirstPartyStorage",
     IDS_CATSXP_SHIELDS_FORGET_FIRST_PARTY_STORAGE_LABEL},
    {"catsxpShieldsCookiesBlockAll", IDS_CATSXP_SHIELDS_COOKIES_BLOCKED},
    {"catsxpShieldsCookiesAllowedAll", IDS_CATSXP_SHIELDS_COOKIES_ALLOWED_ALL},
    {"catsxpShieldsFingerprintingBlocked",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_BLOCKED},
    {"catsxpShieldsFingerprintingBlockedStd",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_BLOCKED_STD},
    {"catsxpShieldsFingerprintingBlockedAgg",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_BLOCKED_AGG},
    {"catsxpShieldsFingerprintingAllowAll",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_ALLOW_ALL},
    {"catsxpShieldsHttpsUpgradeModeDisabled",
     IDS_CATSXP_SHIELDS_HTTPS_UPGRADE_MODE_DISABLED},
    {"catsxpShieldsHttpsUpgradeModeStandard",
     IDS_CATSXP_SHIELDS_HTTPS_UPGRADE_MODE_STANDARD},
    {"catsxpShieldsHttpsUpgradeModeStrict",
     IDS_CATSXP_SHIELDS_HTTPS_UPGRADE_MODE_STRICT},
    {"catsxpShieldsReportSite", IDS_CATSXP_SHIELDS_REPORT_SITE},
    {"catsxpShieldsReportSiteDesc", IDS_CATSXP_SHIELDS_REPORT_SITE_DESC},
    {"catsxpShieldsDownDesc", IDS_CATSXP_SHIELDS_DOWN_DESC},
    {"catsxpShieldsBlockedScriptsLabel",
     IDS_CATSXP_SHIELDS_BLOCKED_SCRIPTS_LABEL},
    {"catsxpShieldsFingerprintingProtectionsAppliedLabel",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_PROTECTIONS_APPLIED_LABEL},
    {"catsxpShieldsLearnMoreLinkText", IDS_CATSXP_SHIELDS_LEARN_MORE_LINK_TEXT},
    {"catsxpShieldsFingerprintingListDescription",
     IDS_CATSXP_SHIELDS_FINGERPRINTING_LIST_DESCRIPTION},
    {"catsxpShieldsAllowedScriptsLabel",
     IDS_CATSXP_SHIELDS_ALLOWED_SCRIPTS_LABEL},
    {"catsxpShieldsBlockedFingerprintsLabel",
     IDS_CATSXP_SHIELDS_BLOCKED_FINGERPRINTS_LABEL},
    {"catsxpShieldsAllowedFingerprintsLabel",
     IDS_CATSXP_SHIELDS_ALLOWED_FINGERPRINTS_LABEL},
    {"catsxpShieldsManaged", IDS_CATSXP_SHIELDS_MANAGED},
    {"catsxpShieldsAllowScriptOnce", IDS_CATSXP_SHIELDS_ALLOW_SCRIPT_ONCE},
    {"catsxpShieldsBlockScript", IDS_CATSXP_SHIELDS_SCRIPT_BLOCK},
    {"catsxpShieldsAllowScriptsAll", IDS_CATSXP_SHIELDS_ALLOW_SCRIPTS_ALL},
    {"catsxpShieldsBlockScriptsAll", IDS_CATSXP_SHIELDS_BLOCK_SCRIPTS_ALL}};

}  // namespace catsxp_shields

#endif  // CATSXP_COMPONENTS_CATSXP_SHIELDS_CORE_COMMON_CATSXP_SHIELD_LOCALIZED_STRINGS_H_
