/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_ISSUERS_TOKEN_ISSUERS_CONFIRMATION_TOKEN_ISSUER_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_ISSUERS_TOKEN_ISSUERS_CONFIRMATION_TOKEN_ISSUER_UTIL_H_

namespace catsxp_ads {

struct IssuersInfo;

bool IsConfirmationTokenIssuerValid(const IssuersInfo& issuers);

}  // namespace catsxp_ads

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_ISSUERS_TOKEN_ISSUERS_CONFIRMATION_TOKEN_ISSUER_UTIL_H_
