/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#include "catsxp/components/catsxp_ads/core/internal/common/resources/country_components.h"

#include <string_view>

#include "base/containers/fixed_flat_set.h"

namespace {

constexpr auto kCountryComponentIds = base::MakeFixedFlatSet<std::string_view>(
    base::sorted_unique,
    {
        "aaimmlceeblnamfkoegoehnpinicgcnj", "aakkjhalljadmndbghodljbjnicbcihc",
        "acedoemlmkefoibbcjnmhgnhgbeggiee", "acolpaaecgjmmahapognpggabhbmalee",
        "admfbchfccbjinpfmjenblapodebdflh", "afbfkfkddhjegoeoailbppgnoamnlgla",
        "afnjhiibmihmffnjjjconicdheaiajho", "agijmfegfamebbgkpephfgdcndcjiojj",
        "aglbacnccepliiieofgadeejlbcinbin", "ahdobjhpfkcooamclgofhedekoomagda",
        "aiabfadmpnlleimdbncfjjdjkpkmdnll", "aikkoklkmnlnnpaodmpioebloalkdhkc",
        "ajbledjkfjhcimkkdlliehdcnmnembcl", "ajhgiodcpkgjlmfebghpkmmgbeniookd",
        "akalojapgkjcaejjgnmabbfjadgbmmee", "amkaaamilegekapcoahoghfedllapaop",
        "amlghgckachldkkajgkkmgfmkpdimnpp", "ampdifbabpclpkgflmpgaccioclggbkd",
        "anakdenhbfifdjfnphggkindkjgnahjl", "appbfnejdbikfjhnccakpkjinlmceihf",
        "bapioeoignilllfekgnnfjlgcjplpeeg", "bbcacimbhjcmodigbdldlnbaallkhjfm",
        "beangncgomibgcpjlaomjjiaipoanjip", "beennkmnfodilfpdnbiejebdpjmcfpjj",
        "bghddfbhpandimbemmiddiaeakpncdlk", "bgmcfljjgonbhiicngcpkkhjjhonbjch",
        "bgpjieoijpcodckababidkinbhomfefp", "biknlamocdecconcgjbdfalpcahepbbl",
        "bndelbgcfpdlanheogdomkllfojihddh", "bneegdnjjoalnoaainfhnkibnencpdbc",
        "bolkogmffelecgdckkjkcdoeedkjolfn", "bpdnkegmhhmbkkifakkbdfpdohfnikbl",
        "cbieoeimppafcebmjoblnjokkjnmbpnm", "cchdcecjnokkojoenpdmeapomiiadhhm",
        "cdadddbmnacicmdknopjccmonfkpeghn", "ceaakiapbhdhhgdpcafjjnkhkphijgfb",
        "cfjijeelflkdkdnbmklaleachbclphal", "cighibkgidfaadlpabiindbfjhhohhem",
        "ckifoeifddolfomffaolikknpdibjngn", "clhfgmbkknnlljcjjdndbolijfbcmkpl",
        "cmclkiaicfglfnapkceekjfcfhfeffka", "cmcpchbolaedginjemnkaabhgnhonpbb",
        "cnhkilmklaplhkhmeklagkflieomabnm", "colccdphhohimnfdfadopmjijbpmlipp",
        "cphjinmjgmbfpanlkcdalbgpechdcago", "cplhacnhgacnbilcggglmfbaohgoahce",
        "dbmnjfgfdddgpkijcjgkccalklpnkbkk", "ddkndjnkoaidlbmhembmnpchejpppaao",
        "dfbfoabmlfkfcjcehgifhcendgmchkip", "dffnadbmacmlnfbjciadchbhiigkllch",
        "dfhfhcoghbmjahaddafdcecoehlknifi", "dfkhplcbcbfnfkdnffgngljifiblhkjk",
        "dfnddfhcifoopjiofbamoemhpmbjgleh", "dgondjoemjcchlejaknbadhlnmkdggpc",
        "dilceojjbmdeilnfkjfbingcbbplmoea", "dimcebfmadlccbgenjbiocbdbigkdjfk",
        "djecgofpbeabpaogeogbhmffmaedcmdi", "djgbgooihdelbhamhpfcipnnmkmccohg",
        "dkaiknabkjfpikccgmapfjpahhpgmapi", "dompfeabkoneajdgepdbekbmilgljbkh",
        "eaaceffjdgdmmipjafnmmgbbihcdfejb", "eagfjojpedemcdibebmpcphkpggblmfk",
        "eapdagpijgablglmibehjhgdabibbbgc", "eckgijabhlpacmadpeipoifldjkjhanl",
        "ecmddiemcpnflgmginponljnibjfgfec", "edmomfmniiepjdjipjjgpohnphpfombc",
        "eeomacbjlgpgflcfcpanbgdggnkjgjfg", "efgncdlbjdebmfaajkhgjoabhadipofd",
        "eghlflgfpjfcajedcllebfdkoamjiekn", "egmahdolieemdiknhofelbfmakkpgeeh",
        "ehbjjancfnmflfdofelfgickejckiafj", "eicpeboflofbhmjnffojkeepmeamlede",
        "eifddhpoeakgdcfobcacnajmiigdmjcp", "eiknfkcmbocncdjgognhdmicomjkfohn",
        "eilgbpkfcdgbbkjjknfigfnhbnpmmcig", "ejeanclolekmknlifbcnacfljkphoacn",
        "ekcjgcnmjdgfakffemilcdlkdbfppgcc", "ekpdmhphmahhbgklbjonllkjgemnpabp",
        "epmncekmjbdfjnpbjkbljhjhpmhiojif", "faiiagfcghochemkpcolhgkhgkkghmmk",
        "falldldilbcpmnblggpnfcnpocdmadef", "fbmogpgfaamiacnafpddbdoofkacdapb",
        "fckhomcmcchdnkcnpbnfmkabiohkmkij", "fdcimhpgambbnnonmhgcfecahhomagmn",
        "fdjfenkjcpkdjfmdnppnmjdncejoloao", "fdnfnclmdkefpapadhahkfbkbhcdlbnl",
        "feabfgikpikbihkdlgjjfeckhdiefgpn", "feodndkapjefeodcdibaoehednfgiech",
        "fflohhkppddgddjdielllhcjplodmimm", "ffoffpfdmlgbhdpofnbcigllbekpkddm",
        "fgdmngghocdjpoehplfiefadjddhcigl", "fhlcoielkkgedbfghchnedhbpafidofg",
        "fjmljfagomnlfpcfmofkifghmappdjjm", "fnfdclcpcfboajmacpoleaoomdehffma",
        "fngidmfnpjlnclpgbjfanoleepflmlcp", "fnlbfnkncdocimbfhecmbncmnebnmpgd",
        "galbglgohakfkbbbninckamibejimkei", "gbakeloejijcmnfkkjhmlkafabnjkihe",
        "gbjopmfmiibnahdcpcnpiijfphafjecm", "gcfmobmmnllghnflcpdahbgnekghcpik",
        "gcgdkkjgfpenleeckcdnobppbejkopmn", "gcmceegpkalmhiffbcimhbolcejfhlmo",
        "gcofakgpldlnmkfdlhiekhpnmmfnhkce", "gednocipkoepmgimojfedfjbaoddmean",
        "gfemfioemadhkglnegokjigffilnhlfl", "gfpgdldhcofmnichcodcecbegiiombdg",
        "ghbgdcbpdlkmekmilibkhekkbkmcaggo", "glgfkakdiicifcfhibbiaabbfobgdmbl",
        "glpfakehepdncmhdehmgapjknhagcakg", "gmbffeancgagjhfhganolgkdjjbhkifd",
        "hapfgappdacbjgoiicciadgljaokkgld", "hbkdbpoanjbnmjnaphghajlknknpapii",
        "hcnlmdoolenccfhdpjcfpbmonhhbdamj", "hdognfafpbgplbihfhjeikdbjejopmgm",
        "hgpgchhancnjeblfpgmepienllabodee", "hicikbeicnjdehccimhcfmncmlgemacd",
        "hilehgnojdnahockbogldhiibebjehck", "hjogbdfgnechhjfbmppbjplecagoimej",
        "hjpajnkpmnbcmeonlmkaclhcmpgakboe", "hlicpfifpepjhomjpallfimioegekege",
        "hlmlekjehbepodbclhffphpomepealeb", "hmdkmionijendeaipllnhgfjkfmcfamf",
        "hmmfmebmlmbieicnnhdhenaajmhkkcmp", "hndagcngfffficbopgpdbiiclcjggdjk",
        "hnokphndhhbelhlobflihginopnfdmde", "hofcnaeimiejcmhbmpjakfmibnaemgil",
        "hpgnhnokgdjholkbbnejkealljpkokij", "ibopaikcdhfhlnlmabmnnpnihdcgbham",
        "icfpbpcoghalafcfkpledmgigfcafehk", "icojdhjdhfbcgcjmacikblcimnhlgfkg",
        "idffmclepnocgbheaaapifnjedebbemg", "ifjfackjnnamjlgjhokbncgjgmikfckn",
        "ilobipjfpibihgknodjpkgfapjmopddo", "implgelnfoaicinlcllbnmllohanhndm",
        "inafkkacgieekodmnpgklbgcoimhbbjn", "ipgmolnlibnijocopinpndikokioegdp",
        "jehahngidiflciljdedkmpeigbpcnpbg", "jfigidafaflonhgennoeoglpegofdhlm",
        "jghliepdemmbcbkkgpmhalcfmahpikkm", "jgjpklfldpdciigalhehcbeoipkmnalo",
        "jhdgjmdpdllcplpcefjigplnikhglokh", "jjioimodfgpgigmfnchmmmapcnjboimn",
        "jkjdfanjdclcaaaaafkhdajeaohljlka", "jlkbcphmknfglhphjinlgbalohfmbmlh",
        "jngcmmpmdhgnncofpknbdclagdmjphon", "jpmddkccjphimoebppplhhdbnedhmpji",
        "jpnibedcbhoinbmeafbkaofdnlacaomj", "kbmojbkeboepadmfoboaegjiikpfhilo",
        "kcpblgnlcbdcehflpgkdbddfocpodncn", "kdgpdjpbijflecojdjnpbdeiogbnogjp",
        "kdkgfpgfegmibjkomnanjfgliaoomkod", "kgiikkblkoigogggekiophbmnilhbjoa",
        "kgonmmpbnggaefggpboakpbencjflmjh", "kiabomkipdfampdmcndnfoekealcdhlo",
        "kieamgmebabfnfpicliejanommefbifl", "kilpomaebmlnodkhfajhojhcobljaihd",
        "kjambpcfghlocmpneimgcmpbjdnjlgfi", "kjegnapkacjhbmjpemknmlgbamkjpngb",
        "klmcmjpjjegahngfjllepopheomhjobc", "klnhkoopdkhmkophdgdahkfjkbjnhinf",
        "kmanpafnkaggejnghgcjldamglefnjab", "kmefmkpmmciafkjachmngdlhbnpdkhpo",
        "kmjhnminfkopincoeldbickclnhdclee", "kngglbabpffgflhfhmkjmnkjnnohfojb",
        "kofpfamhbigbcmcneamgdlnihmldfcph", "kpkbhjghjfaniofhammjlompocgbgmnn",
        "kponghkpdiighmkajilpfekknajemeoh", "laoejkncooflpkdfmdiaphncbmjdgjkb",
        "lccfgdabcbobmkhdkcnlmijciohknlic", "ldjhlaiahaffmghbhjomllgmmkojioee",
        "leidhednofaemccgfpkmimjbaloiphpk", "lgolbgmhhpokhkaeinllmilpljpolcpm",
        "lhbfkadmgihjbbocadbkehgoclbdgbin", "lhlcfcdbhpaophpbeobhfdpceoibnppc",
        "liifknoladjjcdokoeobbgfafbhhfkcl", "ljkbodjkceoplaegdlaefoblchbpmjlg",
        "lligabnjjeeibnbdphakndojhpfhmfjc", "lllechjpiadgcfbkfmdnonkebjdoojoc",
        "lnamingpcjfjmepjiceknaddpmbjdoda", "loglgcjbhonebeidgigbpeaoabcfmjga",
        "lpckgdfeppjnbifogjjfkdmifgepmfoc", "lpgacfifhbhfppmgkpfpkgkgioadnbeo",
        "lpmpihpnlcpiekgfdmbfhilndebafknb", "mabhmogiphfehpeafndhcakmkmenkadh",
        "macdgijgkhmgnlmciipnljjcmpnejmgp", "mambahbokhgbomgjeodbacbbhheoapff",
        "mbbgnjfhkhjjbncfmioedfgildcaapmf", "mbcjiadggpnjhmajjflojbooioagknmd",
        "mcgiclkajndagghopoimhlddjblefpcm", "mdfmnjppfjnchopgbkgaiaemlecmgiij",
        "mdfmodcjgnadhjgegooddcajambcfpnp", "mealonkaoificpegkikieepjclmacogo",
        "mflgmeaoeljbnngmlmegnjohelckbike", "mgkhaklpnjfilhmknnfehdcbcnpdgfni",
        "mhjomiiebloagpljnlbfoedbncgapoog", "mkammconkjkmeafnhkjdifgailommpag",
        "mkbecifgfaolmmfdojfcapaoclifnbhl", "mkfnedalfgfekimacmknhehfhkoaglgc",
        "mnccjcjacenknhojlikgefddoahnkdoe", "mneiabcpepbfnjdochnccpjfnfmibaan",
        "mnejcgglgfdfmgikmdoffknhjbapfogl", "mnggkldejcnongpnkehlclnjmcckjjko",
        "mnmiejkajeoknpgobnkhfajnpkoagpja", "mnmmmnfmednlhagjaeadkdihgfdajaed",
        "mohdnhildabhfgokigfgeijgipinchig", "mpajpkgidcmjcepdpccdniflmbbllmei",
        "mpbcmaoaljjfolpbehpcgnodhieagnlo", "mpjccpfncolmdagegdooepdanmilmpim",
        "nbfgdkhnimcdkfekfmhaggkdnebaaijp", "nccpmjhpipijcepbgjikildlabdepmbn",
        "nceibhioljfgodpgfhmcomahnhldllco", "nckblgmfnddbcndannniaidgbipognlg",
        "ndanebclehbmfhojpbbilcmcgemnjmdd", "ngfhlhkejnabfogkaggnhefkclkmhjbg",
        "ngfpfgabjjmlbaogohpdlcjhcdhafopm", "njjjmijbnhcanaehbbmppklngmchdlbi",
        "nldgomgliheodnnkhldiflimdegipcng", "nmoogilknbhgialkboochfkfcinakgen",
        "nnkghbdbhaefdjjkdclcedlcbmmndade", "nojkichnkldaggknfhlfgnpdhhcbdbhg",
        "oakhpekdjemkfmikaoamdklodhmoolcf", "ocbapoadphebieejhfbnjndbpnjbgaaj",
        "ocedfngpepfnjginldbffpfeddbffjah", "ocjccogeamlncdngbfknhekpmghpcboj",
        "oddhjfkghbjhpnjkocoglcinphefbhnj", "oeajccngipehdblecdhnodlokiljofol",
        "ofnhkoanbnfbnmdanagjigncdbmbnojn", "ognoaloaknkdgdadbiicbnbbcdjfgajp",
        "okfanndbomojomobpiofnipegaabnknh", "okhlolhncpiiiilpdppcghokgejdback",
        "okhpfnodjehlkjniijmmgehhaclkecbd", "okioofncippomodkoannlfbhiiobnffn",
        "olpgpnlkeagfdmifmjbeccpcoipdnfnk", "onlcdinapolamokmfidhocaehmciljaj",
        "oocdddgdfbcaddoiplmnhlkpnhgjchmo", "oofmhmombbcklmlooaokpdgakcadnhcc",
        "paaalohpfacejabmapaidknpaiklnpkn", "pbmpflmcpbpkmingfbhoeobeneaoihbm",
        "pibnnadhchoohcaopijpbfpidedhdjgd", "pjpagcaflckjjjdlmeljlijlljkkfocc",
        "pkfbnlbeeofdalfggmngnanolhihmdca", "plfbddpagoppdccdfclpcfijbkfndhjc",
        "pliaehbkakmiabpphhmdhhpbioildina", "pmhbcmpfpfiojhondabdpfkdmacicfdm",
        "pmocifpjnahkpgpdfmkcedjdmmmblebb", "pnccokpnnhembfmbbehhdlojihhneelm",
        "pobamhlogingdnpinpkjiddfkppeepdn", "pogpodghagfjofbgcebipmcllfngjfch",
        "ppnehlhakhdmgkphehdmcjmjccloigmd",
    });

}  // namespace

namespace catsxp_ads {

bool IsValidCountryComponentId(const std::string& id) {
  return kCountryComponentIds.contains(id);
}

}  // namespace catsxp_ads
