/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_CONFIRMATIONS_USER_DATA_BUILDER_FIXED_CONFIRMATION_FIXED_USER_DATA_BUILDER_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_CONFIRMATIONS_USER_DATA_BUILDER_FIXED_CONFIRMATION_FIXED_USER_DATA_BUILDER_H_

#include "base/values.h"

namespace catsxp_ads {

struct TransactionInfo;

base::DictValue BuildFixedUserData(const TransactionInfo& transaction);

}  // namespace catsxp_ads

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_CONFIRMATIONS_USER_DATA_BUILDER_FIXED_CONFIRMATION_FIXED_USER_DATA_BUILDER_H_
