/* Copyright (c) 2020 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_ELIGIBLE_ADS_EXCLUSION_RULES_TEST_DAYPART_EXCLUSION_RULE_TEST_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_ELIGIBLE_ADS_EXCLUSION_RULES_TEST_DAYPART_EXCLUSION_RULE_TEST_UTIL_H_

namespace catsxp_ads::test {

int ConvertHoursAndMinutesToTotalMinutes(int hours, int minutes);

}  // namespace catsxp_ads::test

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_ELIGIBLE_ADS_EXCLUSION_RULES_TEST_DAYPART_EXCLUSION_RULE_TEST_UTIL_H_
