/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_USER_DATA_DYNAMIC_DIAGNOSTIC_ID_USER_DATA_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_USER_DATA_DYNAMIC_DIAGNOSTIC_ID_USER_DATA_H_

#include "base/values.h"

namespace catsxp_ads {

base::DictValue BuildDiagnosticIdUserData();

}  // namespace catsxp_ads

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_USER_DATA_DYNAMIC_DIAGNOSTIC_ID_USER_DATA_H_
