/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_CONTENT_SETTINGS_CONTENT_SETTINGS_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_CONTENT_SETTINGS_CONTENT_SETTINGS_UTIL_H_

namespace catsxp_ads {

bool IsJavaScriptAllowed();

}  // namespace catsxp_ads

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_CONTENT_SETTINGS_CONTENT_SETTINGS_UTIL_H_
