/* Copyright (c) 2020 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_PERMISSION_RULES_TEST_CONFIRMATION_TOKENS_PERMISSION_RULE_TEST_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_PERMISSION_RULES_TEST_CONFIRMATION_TOKENS_PERMISSION_RULE_TEST_UTIL_H_

namespace catsxp_ads::test {

void ForceConfirmationTokensPermissionRule();

}  // namespace catsxp_ads::test

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_SERVING_PERMISSION_RULES_TEST_CONFIRMATION_TOKENS_PERMISSION_RULE_TEST_UTIL_H_
