/* Copyright (c) 2020 The Catsxp Authors. All rights reserved. */

#ifndef CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REFILL_CONFIRMATION_TOKENS_TEST_REFILL_CONFIRMATION_TOKENS_TEST_UTIL_H_
#define CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REFILL_CONFIRMATION_TOKENS_TEST_REFILL_CONFIRMATION_TOKENS_TEST_UTIL_H_

#include <string>

namespace catsxp_ads::test {

std::string BuildRequestSignedTokensUrlResponseBody();
std::string BuildGetSignedTokensUrlResponseBody();

}  // namespace catsxp_ads::test

#endif  // CATSXP_COMPONENTS_CATSXP_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REFILL_CONFIRMATION_TOKENS_TEST_REFILL_CONFIRMATION_TOKENS_TEST_UTIL_H_
