/* Copyright (c) 2023 The Catsxp Authors. All rights reserved. */

// Types for Player
export enum types {
  PLAYLIST_ITEM_SELECTED = '@@playlist/PLAYLIST_ITEM_SELECTED',

  PLAYER_STARTED_PLAYING_ITEM = '@@playlist/PLAYER_STARTED_PLAYING_ITEM',

  PLAYER_STOPPED_PLAYING_ITEM = '@@playlist/PLAYER_STOPPED_PLAYING_ITEM',

  PLAYER_PLAY_NEXT_ITEM = '@@playlist/PLAYER_PLAY_NEXT_ITEM',

  PLAYER_PLAY_PREVIOUS_ITEM = '@@playlist/PLAYER_PLAY_PREVIOUS_ITEM',

  PLAYER_TOGGLE_SHUFFLE = '@@playlist/PLAYER_TOGGLE_SHUFFLE',

  PLAYER_ADVANCE_LOOP_MODE = '@@playlist/PLAYER_ADVANCE_LOOP_MODE',

  PLAYER_TOGGLE_AUTO_PLAY = '@@playlist/PLAYER_TOGGLE_AUTO_PLAY',

  SELECTED_PLAYLIST_UPDATED = '@@playlist/SELECTED_PLAYLIST_UPDATED',

  UNLOAD_PLAYLIST = '@@playlist/UNLOAD_PLAYLIST'
}
